// Job Notification Tracker - Realistic Indian Tech Jobs Dataset

const JOBS_DATA = [
  {
    id: 1,
    title: "SDE Intern",
    company: "Amazon",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Java", "Data Structures", "Algorithms"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "₹25k–₹40k/month Internship",
    applyUrl: "https://amazon.jobs/en/jobs/intern-sde",
    description: "Join Amazon's engineering team as an SDE Intern. Work on scalable systems, collaborate with experienced engineers, and contribute to products used by millions. Strong problem-solving skills and knowledge of data structures required."
  },
  {
    id: 2,
    title: "Graduate Engineer Trainee",
    company: "Infosys",
    location: "Mysore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "Python", "SQL"],
    source: "Naukri",
    postedDaysAgo: 1,
    salaryRange: "3–5 LPA",
    applyUrl: "https://infosys.com/careers/get",
    description: "Infosys is hiring fresh graduates for our GET program. Comprehensive training provided in latest technologies. Work on enterprise projects for global clients. Excellent learning opportunities and career growth in a Fortune 500 company."
  },
  {
    id: 3,
    title: "Frontend Intern",
    company: "Flipkart",
    location: "Bangalore",
    mode: "Remote",
    experience: "Fresher",
    skills: ["React", "JavaScript", "CSS"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "₹20k–₹35k/month Internship",
    applyUrl: "https://flipkart.com/careers/intern",
    description: "Build user interfaces for India's leading e-commerce platform. Work with React, modern JavaScript, and responsive design. Collaborate with product and design teams to create seamless shopping experiences for millions of users."
  },
  {
    id: 4,
    title: "Junior Backend Developer",
    company: "Swiggy",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Node.js", "MongoDB", "REST APIs"],
    source: "Indeed",
    postedDaysAgo: 0,
    salaryRange: "6–10 LPA",
    applyUrl: "https://swiggy.com/careers/backend",
    description: "Join Swiggy's backend team to build scalable food delivery systems. Work on microservices, APIs, and database optimization. Handle high-traffic scenarios and ensure system reliability for millions of daily orders."
  },
  {
    id: 5,
    title: "QA Intern",
    company: "TCS",
    location: "Pune",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Manual Testing", "Selenium", "JIRA"],
    source: "Naukri",
    postedDaysAgo: 4,
    salaryRange: "₹15k–₹25k/month Internship",
    applyUrl: "https://tcs.com/careers/qa-intern",
    description: "Learn software testing methodologies at TCS. Work on test case design, execution, and defect tracking. Gain exposure to automation tools and agile practices. Great opportunity to start your QA career with a global IT leader."
  },
  {
    id: 6,
    title: "Data Analyst Intern",
    company: "Razorpay",
    location: "Bangalore",
    mode: "Remote",
    experience: "Fresher",
    skills: ["Python", "SQL", "Excel", "Tableau"],
    source: "LinkedIn",
    postedDaysAgo: 5,
    salaryRange: "₹30k–₹45k/month Internship",
    applyUrl: "https://razorpay.com/jobs/data-analyst",
    description: "Analyze payment data and generate insights for India's leading fintech. Work with large datasets, create dashboards, and support data-driven decision making. Learn from experienced data scientists in a fast-paced startup environment."
  },
  {
    id: 7,
    title: "Java Developer (0-1)",
    company: "Wipro",
    location: "Hyderabad",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Java", "Spring Boot", "MySQL"],
    source: "Naukri",
    postedDaysAgo: 2,
    salaryRange: "3–5 LPA",
    applyUrl: "https://wipro.com/careers/java-dev",
    description: "Develop enterprise Java applications for global clients. Work with Spring framework, microservices, and cloud technologies. Wipro offers excellent training programs and opportunities to work on diverse projects across industries."
  },
  {
    id: 8,
    title: "Python Developer (Fresher)",
    company: "Zoho",
    location: "Chennai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Python", "Django", "PostgreSQL"],
    source: "Indeed",
    postedDaysAgo: 1,
    salaryRange: "4–6 LPA",
    applyUrl: "https://zoho.com/careers/python",
    description: "Build web applications using Python and Django at Zoho. Work on SaaS products used by millions worldwide. Great work culture, no-nonsense approach, and focus on engineering excellence. Freshers with strong programming skills welcome."
  },
  {
    id: 9,
    title: "React Developer (1-3)",
    company: "PhonePe",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "Redux", "TypeScript", "Jest"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "10–18 LPA",
    applyUrl: "https://phonepe.com/careers/react",
    description: "Build India's most popular payment app's frontend. Work with React, TypeScript, and modern web technologies. Handle complex state management and ensure smooth UX for 400M+ users. Competitive salary and ESOP benefits."
  },
  {
    id: 10,
    title: "Full Stack Developer Intern",
    company: "CRED",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["React", "Node.js", "MongoDB"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "₹35k–₹50k/month Internship",
    applyUrl: "https://cred.club/careers/intern",
    description: "Join CRED's engineering team to build premium fintech experiences. Work on both frontend and backend, learn from top engineers, and contribute to products used by India's most creditworthy individuals. Fast-paced startup culture."
  },
  {
    id: 11,
    title: "DevOps Intern",
    company: "Accenture",
    location: "Pune",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Docker", "Kubernetes", "AWS", "Linux"],
    source: "Naukri",
    postedDaysAgo: 6,
    salaryRange: "₹20k–₹30k/month Internship",
    applyUrl: "https://accenture.com/careers/devops",
    description: "Learn DevOps practices at Accenture. Work with containerization, CI/CD pipelines, and cloud infrastructure. Gain hands-on experience with industry-standard tools and methodologies while working on enterprise client projects."
  },
  {
    id: 12,
    title: "Android Developer (0-1)",
    company: "Paytm",
    location: "Noida",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Kotlin", "Android SDK", "MVVM"],
    source: "Indeed",
    postedDaysAgo: 4,
    salaryRange: "6–10 LPA",
    applyUrl: "https://paytm.com/careers/android",
    description: "Build features for Paytm's Android app used by 350M+ users. Work with Kotlin, modern Android architecture, and performance optimization. Collaborate with product and design teams to deliver seamless mobile experiences."
  },
  {
    id: 13,
    title: "Machine Learning Intern",
    company: "Freshworks",
    location: "Chennai",
    mode: "Remote",
    experience: "Fresher",
    skills: ["Python", "TensorFlow", "Scikit-learn"],
    source: "LinkedIn",
    postedDaysAgo: 7,
    salaryRange: "₹30k–₹40k/month Internship",
    applyUrl: "https://freshworks.com/careers/ml",
    description: "Work on ML models for customer engagement products. Build recommendation systems, NLP features, and predictive analytics. Learn from experienced ML engineers in a product-focused SaaS company with global reach."
  },
  {
    id: 14,
    title: "UI/UX Designer Intern",
    company: "Juspay",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Figma", "Adobe XD", "User Research"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "₹25k–₹35k/month Internship",
    applyUrl: "https://juspay.in/careers/design",
    description: "Design payment experiences for India's leading payment orchestration platform. Work on mobile and web interfaces, conduct user research, and create design systems. Collaborate with engineers to bring designs to life."
  },
  {
    id: 15,
    title: "Backend Engineer (1-3)",
    company: "Capgemini",
    location: "Mumbai",
    mode: "Onsite",
    experience: "1-3",
    skills: ["Java", "Spring Boot", "Microservices", "Kafka"],
    source: "Naukri",
    postedDaysAgo: 5,
    salaryRange: "8–12 LPA",
    applyUrl: "https://capgemini.com/careers/backend",
    description: "Develop scalable backend systems for enterprise clients. Work with microservices architecture, event-driven systems, and cloud platforms. Capgemini offers global exposure and opportunities to work on cutting-edge technologies."
  },
  { id: 16, title: "Cloud Engineer (0-1)", company: "IBM", location: "Bangalore", mode: "Hybrid", experience: "0-1", skills: ["AWS", "Azure", "Terraform"], source: "Indeed", postedDaysAgo: 3, salaryRange: "5–8 LPA", applyUrl: "https://ibm.com/careers/cloud", description: "Work on cloud infrastructure and migration projects. Learn AWS, Azure, and infrastructure as code. IBM provides excellent training and certification opportunities for cloud technologies." },
  { id: 17, title: "Data Engineer Intern", company: "Oracle", location: "Hyderabad", mode: "Onsite", experience: "Fresher", skills: ["SQL", "Python", "ETL", "Spark"], source: "Naukri", postedDaysAgo: 8, salaryRange: "₹25k–₹35k/month Internship", applyUrl: "https://oracle.com/careers/data", description: "Build data pipelines and ETL processes for enterprise databases. Work with big data technologies and learn from Oracle's database experts. Great opportunity to start your data engineering career." },
  { id: 18, title: "iOS Developer (1-3)", company: "SAP", location: "Bangalore", mode: "Hybrid", experience: "1-3", skills: ["Swift", "iOS SDK", "Core Data"], source: "LinkedIn", postedDaysAgo: 1, salaryRange: "10–15 LPA", applyUrl: "https://sap.com/careers/ios", description: "Develop iOS applications for SAP's enterprise mobility solutions. Work with Swift, modern iOS frameworks, and enterprise integration. SAP offers excellent benefits and work-life balance." },
  { id: 19, title: "Security Analyst Intern", company: "Dell", location: "Bangalore", mode: "Onsite", experience: "Fresher", skills: ["Cybersecurity", "Network Security", "Linux"], source: "Indeed", postedDaysAgo: 9, salaryRange: "₹20k–₹30k/month Internship", applyUrl: "https://dell.com/careers/security", description: "Learn cybersecurity practices at Dell. Work on threat analysis, vulnerability assessment, and security monitoring. Gain exposure to enterprise security tools and best practices." },
  { id: 20, title: "Product Manager Intern", company: "Cognizant", location: "Chennai", mode: "Hybrid", experience: "Fresher", skills: ["Product Strategy", "Analytics", "Agile"], source: "Naukri", postedDaysAgo: 4, salaryRange: "₹30k–₹40k/month Internship", applyUrl: "https://cognizant.com/careers/pm", description: "Learn product management in a global IT services company. Work with engineering teams, analyze user data, and contribute to product roadmaps. Great stepping stone for a PM career." },
  { id: 21, title: "Frontend Developer (1-3)", company: "Myntra", location: "Bangalore", mode: "Hybrid", experience: "1-3", skills: ["React", "Next.js", "CSS", "Performance"], source: "LinkedIn", postedDaysAgo: 2, salaryRange: "12–18 LPA", applyUrl: "https://myntra.com/careers/frontend", description: "Build India's leading fashion e-commerce platform. Work on performance optimization, responsive design, and modern web technologies. Handle millions of users during sale events." },
  { id: 22, title: "SDE-1", company: "Ola", location: "Bangalore", mode: "Onsite", experience: "0-1", skills: ["Java", "Spring", "MySQL", "Redis"], source: "Indeed", postedDaysAgo: 0, salaryRange: "8–12 LPA", applyUrl: "https://ola.com/careers/sde", description: "Join Ola's engineering team to build ride-hailing solutions. Work on backend systems, real-time matching algorithms, and scalable architectures. Fast-paced environment with significant impact." },
  { id: 23, title: "Test Automation Engineer", company: "HCL", location: "Noida", mode: "Onsite", experience: "1-3", skills: ["Selenium", "Java", "TestNG", "CI/CD"], source: "Naukri", postedDaysAgo: 6, salaryRange: "5–9 LPA", applyUrl: "https://hcl.com/careers/qa", description: "Automate testing for enterprise applications. Build test frameworks, integrate with CI/CD pipelines, and ensure quality. HCL offers stable career growth and diverse project exposure." },
  { id: 24, title: "Blockchain Developer Intern", company: "Tech Mahindra", location: "Pune", mode: "Hybrid", experience: "Fresher", skills: ["Solidity", "Ethereum", "Web3.js"], source: "LinkedIn", postedDaysAgo: 10, salaryRange: "₹25k–₹40k/month Internship", applyUrl: "https://techmahindra.com/careers/blockchain", description: "Explore blockchain technology and build decentralized applications. Work on smart contracts, DApps, and Web3 integration. Emerging technology with high growth potential." },
  { id: 25, title: "Site Reliability Engineer (1-3)", company: "Zomato", location: "Gurgaon", mode: "Hybrid", experience: "1-3", skills: ["Kubernetes", "Prometheus", "Python", "Linux"], source: "Indeed", postedDaysAgo: 3, salaryRange: "12–20 LPA", applyUrl: "https://zomato.com/careers/sre", description: "Ensure reliability and performance of Zomato's food delivery platform. Work on monitoring, incident response, and infrastructure automation. Handle high-traffic scenarios and system optimization." },
  { id: 26, title: "Business Analyst Intern", company: "Deloitte", location: "Mumbai", mode: "Onsite", experience: "Fresher", skills: ["Excel", "SQL", "Business Analysis"], source: "Naukri", postedDaysAgo: 5, salaryRange: "₹20k–₹30k/month Internship", applyUrl: "https://deloitte.com/careers/ba", description: "Analyze business requirements and support digital transformation projects. Work with stakeholders, create documentation, and learn consulting methodologies at a Big 4 firm." },
  { id: 27, title: "React Native Developer (0-1)", company: "Urban Company", location: "Gurgaon", mode: "Remote", experience: "0-1", skills: ["React Native", "JavaScript", "Redux"], source: "LinkedIn", postedDaysAgo: 1, salaryRange: "6–10 LPA", applyUrl: "https://urbancompany.com/careers/rn", description: "Build cross-platform mobile apps for India's leading home services platform. Work with React Native, handle complex app states, and deliver smooth user experiences for millions of users." },
  { id: 28, title: "Data Scientist (1-3)", company: "Walmart Labs", location: "Bangalore", mode: "Hybrid", experience: "1-3", skills: ["Python", "Machine Learning", "SQL", "Statistics"], source: "Indeed", postedDaysAgo: 4, salaryRange: "15–25 LPA", applyUrl: "https://walmartlabs.com/careers/ds", description: "Build ML models for retail analytics and personalization. Work on recommendation systems, demand forecasting, and customer insights. Walmart Labs offers competitive compensation and cutting-edge projects." },
  { id: 29, title: "Embedded Systems Intern", company: "Bosch", location: "Bangalore", mode: "Onsite", experience: "Fresher", skills: ["C", "Embedded C", "Microcontrollers"], source: "Naukri", postedDaysAgo: 7, salaryRange: "₹18k–₹28k/month Internship", applyUrl: "https://bosch.com/careers/embedded", description: "Work on embedded systems for automotive and IoT products. Learn firmware development, hardware interfacing, and real-time systems. Bosch provides excellent engineering training." },
  { id: 30, title: "Salesforce Developer (0-1)", company: "LTI Mindtree", location: "Chennai", mode: "Onsite", experience: "0-1", skills: ["Salesforce", "Apex", "Lightning"], source: "LinkedIn", postedDaysAgo: 2, salaryRange: "4–7 LPA", applyUrl: "https://ltimindtree.com/careers/salesforce", description: "Develop and customize Salesforce CRM solutions for enterprise clients. Learn Salesforce platform, Apex programming, and Lightning components. High demand skill with excellent career prospects." },
  { id: 31, title: "Game Developer Intern", company: "Nazara Technologies", location: "Mumbai", mode: "Hybrid", experience: "Fresher", skills: ["Unity", "C#", "Game Design"], source: "Indeed", postedDaysAgo: 8, salaryRange: "₹20k–₹35k/month Internship", applyUrl: "https://nazara.com/careers/game", description: "Create mobile games for India's leading gaming company. Work with Unity engine, implement game mechanics, and optimize performance. Great opportunity for gaming enthusiasts." },
  { id: 32, title: "Backend Developer (3-5)", company: "Dream11", location: "Mumbai", mode: "Hybrid", experience: "3-5", skills: ["Node.js", "MongoDB", "Redis", "Microservices"], source: "LinkedIn", postedDaysAgo: 1, salaryRange: "20–35 LPA", applyUrl: "https://dream11.com/careers/backend", description: "Build scalable backend for India's largest fantasy sports platform. Handle millions of concurrent users, real-time data processing, and high-traffic scenarios. Competitive salary and ESOP benefits." },
  { id: 33, title: "Technical Writer Intern", company: "Adobe", location: "Noida", mode: "Remote", experience: "Fresher", skills: ["Technical Writing", "Documentation", "APIs"], source: "Naukri", postedDaysAgo: 6, salaryRange: "₹25k–₹35k/month Internship", applyUrl: "https://adobe.com/careers/writer", description: "Create technical documentation for Adobe's products and APIs. Write clear, concise guides and tutorials. Learn from experienced technical writers in a global software company." },
  { id: 34, title: "Flutter Developer (1-3)", company: "Meesho", location: "Bangalore", mode: "Hybrid", experience: "1-3", skills: ["Flutter", "Dart", "Firebase"], source: "LinkedIn", postedDaysAgo: 0, salaryRange: "10–16 LPA", applyUrl: "https://meesho.com/careers/flutter", description: "Build cross-platform apps for India's leading social commerce platform. Work with Flutter, implement complex UIs, and optimize app performance for millions of resellers and customers." },
  { id: 35, title: "Network Engineer (0-1)", company: "Cisco", location: "Bangalore", mode: "Onsite", experience: "0-1", skills: ["Networking", "CCNA", "Routing", "Switching"], source: "Indeed", postedDaysAgo: 9, salaryRange: "5–8 LPA", applyUrl: "https://cisco.com/careers/network", description: "Design and maintain network infrastructure for enterprise clients. Work with routers, switches, and network security. Cisco offers excellent certification programs and career development." },
  { id: 36, title: "Angular Developer (1-3)", company: "Mphasis", location: "Pune", mode: "Onsite", experience: "1-3", skills: ["Angular", "TypeScript", "RxJS"], source: "Naukri", postedDaysAgo: 3, salaryRange: "7–12 LPA", applyUrl: "https://mphasis.com/careers/angular", description: "Develop enterprise web applications using Angular framework. Work on complex SPAs, state management, and performance optimization for banking and financial services clients." },
  { id: 37, title: "AI/ML Engineer (1-3)", company: "Navi", location: "Bangalore", mode: "Hybrid", experience: "1-3", skills: ["Python", "TensorFlow", "NLP", "Computer Vision"], source: "LinkedIn", postedDaysAgo: 2, salaryRange: "15–22 LPA", applyUrl: "https://navi.com/careers/ml", description: "Build AI models for fintech products. Work on credit scoring, fraud detection, and personalization. Navi offers competitive compensation and opportunity to work on impactful ML problems." },
  { id: 38, title: "SAP Consultant Intern", company: "EY", location: "Gurgaon", mode: "Onsite", experience: "Fresher", skills: ["SAP", "Business Process", "ERP"], source: "Indeed", postedDaysAgo: 5, salaryRange: "₹22k–₹32k/month Internship", applyUrl: "https://ey.com/careers/sap", description: "Learn SAP ERP systems and business consulting. Work on implementation projects for enterprise clients. EY provides structured training and Big 4 consulting experience." },
  { id: 39, title: "Go Developer (1-3)", company: "Gojek", location: "Bangalore", mode: "Hybrid", experience: "1-3", skills: ["Golang", "Microservices", "gRPC", "Docker"], source: "LinkedIn", postedDaysAgo: 1, salaryRange: "12–18 LPA", applyUrl: "https://gojek.com/careers/go", description: "Build high-performance backend services using Go. Work on microservices architecture, distributed systems, and real-time processing for Southeast Asia's super app." },
  { id: 40, title: "Scrum Master (1-3)", company: "Publicis Sapient", location: "Noida", mode: "Hybrid", experience: "1-3", skills: ["Agile", "Scrum", "JIRA", "Facilitation"], source: "Naukri", postedDaysAgo: 4, salaryRange: "8–14 LPA", applyUrl: "https://publicissapient.com/careers/scrum", description: "Facilitate agile ceremonies and remove impediments for engineering teams. Work with cross-functional teams on digital transformation projects for global clients." },
  { id: 41, title: "Python Backend Developer (0-1)", company: "Dunzo", location: "Bangalore", mode: "Remote", experience: "0-1", skills: ["Python", "Django", "PostgreSQL", "Redis"], source: "LinkedIn", postedDaysAgo: 0, salaryRange: "6–10 LPA", applyUrl: "https://dunzo.com/careers/python", description: "Build backend systems for hyperlocal delivery platform. Work on order management, routing algorithms, and real-time tracking. Fast-paced startup environment with significant learning." },
  { id: 42, title: "Cybersecurity Engineer (1-3)", company: "PwC", location: "Bangalore", mode: "Onsite", experience: "1-3", skills: ["Penetration Testing", "Security Audit", "SIEM"], source: "Indeed", postedDaysAgo: 7, salaryRange: "10–16 LPA", applyUrl: "https://pwc.com/careers/security", description: "Conduct security assessments and penetration testing for enterprise clients. Work on vulnerability management, incident response, and security consulting at a Big 4 firm." },
  { id: 43, title: "Vue.js Developer (1-3)", company: "Licious", location: "Bangalore", mode: "Hybrid", experience: "1-3", skills: ["Vue.js", "Vuex", "JavaScript", "Nuxt"], source: "LinkedIn", postedDaysAgo: 3, salaryRange: "8–14 LPA", applyUrl: "https://licious.com/careers/vue", description: "Build frontend for India's leading fresh meat and seafood brand. Work with Vue.js, create responsive interfaces, and optimize for mobile-first experiences." },
  { id: 44, title: "ETL Developer (0-1)", company: "Genpact", location: "Hyderabad", mode: "Onsite", experience: "0-1", skills: ["Informatica", "SQL", "Data Warehousing"], source: "Naukri", postedDaysAgo: 6, salaryRange: "4–7 LPA", applyUrl: "https://genpact.com/careers/etl", description: "Develop ETL pipelines for data integration projects. Work with Informatica, SQL, and data warehousing concepts. Genpact offers stable career in data engineering domain." },
  { id: 45, title: "Mobile QA Engineer (1-3)", company: "Byju's", location: "Bangalore", mode: "Hybrid", experience: "1-3", skills: ["Appium", "Mobile Testing", "Java", "TestNG"], source: "LinkedIn", postedDaysAgo: 2, salaryRange: "6–11 LPA", applyUrl: "https://byjus.com/careers/qa", description: "Test mobile applications for India's leading edtech platform. Automate test cases, perform regression testing, and ensure app quality across devices and OS versions." },
  { id: 46, title: "Rust Developer (1-3)", company: "Polygon", location: "Remote", mode: "Remote", experience: "1-3", skills: ["Rust", "Blockchain", "Systems Programming"], source: "LinkedIn", postedDaysAgo: 1, salaryRange: "18–30 LPA", applyUrl: "https://polygon.technology/careers/rust", description: "Build blockchain infrastructure using Rust. Work on high-performance systems, consensus mechanisms, and decentralized protocols. Cutting-edge technology with global impact." },
  { id: 47, title: "Automation Engineer Intern", company: "Siemens", location: "Bangalore", mode: "Onsite", experience: "Fresher", skills: ["PLC", "SCADA", "Industrial Automation"], source: "Indeed", postedDaysAgo: 8, salaryRange: "₹18k–₹28k/month Internship", applyUrl: "https://siemens.com/careers/automation", description: "Learn industrial automation and control systems. Work on PLC programming, SCADA systems, and factory automation projects. Siemens provides excellent engineering training." },
  { id: 48, title: "Kotlin Developer (1-3)", company: "Grofers (Blinkit)", location: "Gurgaon", mode: "Hybrid", experience: "1-3", skills: ["Kotlin", "Android", "MVVM", "Coroutines"], source: "LinkedIn", postedDaysAgo: 0, salaryRange: "10–16 LPA", applyUrl: "https://blinkit.com/careers/kotlin", description: "Develop Android app for quick commerce platform. Work with Kotlin, modern Android architecture, and real-time features. Handle high-traffic scenarios during peak hours." },
  { id: 49, title: "Technical Support Engineer (0-1)", company: "Microsoft", location: "Hyderabad", mode: "Hybrid", experience: "0-1", skills: ["Windows", "Azure", "Troubleshooting"], source: "Naukri", postedDaysAgo: 5, salaryRange: "5–8 LPA", applyUrl: "https://microsoft.com/careers/support", description: "Provide technical support for Microsoft products and cloud services. Troubleshoot issues, assist customers, and learn Azure platform. Great entry point into Microsoft ecosystem." },
  { id: 50, title: "Full Stack Developer (1-3)", company: "Cure.fit", location: "Bangalore", mode: "Hybrid", experience: "1-3", skills: ["React", "Node.js", "MongoDB", "AWS"], source: "LinkedIn", postedDaysAgo: 3, salaryRange: "10–16 LPA", applyUrl: "https://curefit.com/careers/fullstack", description: "Build health and fitness platform features end-to-end. Work on web and mobile apps, backend APIs, and cloud infrastructure. Impact millions of users' health journeys." },
  { id: 51, title: "Performance Engineer (1-3)", company: "Akamai", location: "Bangalore", mode: "Hybrid", experience: "1-3", skills: ["Performance Testing", "JMeter", "LoadRunner"], source: "Indeed", postedDaysAgo: 4, salaryRange: "9–15 LPA", applyUrl: "https://akamai.com/careers/performance", description: "Test and optimize performance of web applications and CDN services. Work with load testing tools, analyze bottlenecks, and ensure scalability for global traffic." },
  { id: 52, title: "Content Developer Intern", company: "Unacademy", location: "Bangalore", mode: "Remote", experience: "Fresher", skills: ["Content Writing", "Education", "Video Scripts"], source: "LinkedIn", postedDaysAgo: 2, salaryRange: "₹20k–₹30k/month Internship", applyUrl: "https://unacademy.com/careers/content", description: "Create educational content for India's largest learning platform. Write scripts, develop course materials, and collaborate with educators. Great opportunity for education enthusiasts." },
  { id: 53, title: "Scala Developer (3-5)", company: "Goldman Sachs", location: "Bangalore", mode: "Onsite", experience: "3-5", skills: ["Scala", "Akka", "Functional Programming", "Spark"], source: "LinkedIn", postedDaysAgo: 1, salaryRange: "25–40 LPA", applyUrl: "https://goldmansachs.com/careers/scala", description: "Build high-performance trading systems using Scala. Work on distributed systems, real-time data processing, and financial applications. Top-tier compensation and challenging problems." },
  { id: 54, title: "RPA Developer (0-1)", company: "UiPath", location: "Bangalore", mode: "Hybrid", experience: "0-1", skills: ["UiPath", "Automation", "VB.NET"], source: "Naukri", postedDaysAgo: 6, salaryRange: "5–9 LPA", applyUrl: "https://uipath.com/careers/rpa", description: "Develop robotic process automation solutions for enterprise clients. Learn UiPath platform, build automation workflows, and optimize business processes." },
  { id: 55, title: "Graphics Designer Intern", company: "Canva", location: "Remote", mode: "Remote", experience: "Fresher", skills: ["Photoshop", "Illustrator", "UI Design"], source: "LinkedIn", postedDaysAgo: 0, salaryRange: "₹25k–₹40k/month Internship", applyUrl: "https://canva.com/careers/design", description: "Create visual designs for Canva's design platform. Work on templates, illustrations, and marketing materials. Learn from world-class designers in a global design company." },
  { id: 56, title: "Perl Developer (1-3)", company: "Booking.com", location: "Bangalore", mode: "Hybrid", experience: "1-3", skills: ["Perl", "MySQL", "Web Development"], source: "Indeed", postedDaysAgo: 7, salaryRange: "12–18 LPA", applyUrl: "https://booking.com/careers/perl", description: "Maintain and enhance Perl-based systems for global travel platform. Work on backend services, database optimization, and legacy system modernization." },
  { id: 57, title: "Firmware Engineer (1-3)", company: "Qualcomm", location: "Hyderabad", mode: "Onsite", experience: "1-3", skills: ["C", "Embedded Systems", "RTOS"], source: "Naukri", postedDaysAgo: 5, salaryRange: "10–16 LPA", applyUrl: "https://qualcomm.com/careers/firmware", description: "Develop firmware for mobile chipsets and wireless technologies. Work on low-level programming, hardware interfaces, and real-time systems. Qualcomm offers cutting-edge semiconductor work." },
  { id: 58, title: "Shopify Developer (0-1)", company: "Shiprocket", location: "New Delhi", mode: "Remote", experience: "0-1", skills: ["Shopify", "Liquid", "JavaScript", "APIs"], source: "LinkedIn", postedDaysAgo: 3, salaryRange: "4–7 LPA", applyUrl: "https://shiprocket.com/careers/shopify", description: "Build and customize Shopify stores for e-commerce clients. Work with Liquid templating, Shopify APIs, and app integrations. Growing demand in e-commerce space." },
  { id: 59, title: "WordPress Developer (0-1)", company: "Bluehost India", location: "Mumbai", mode: "Hybrid", experience: "0-1", skills: ["WordPress", "PHP", "MySQL", "WooCommerce"], source: "Indeed", postedDaysAgo: 9, salaryRange: "3–6 LPA", applyUrl: "https://bluehost.in/careers/wordpress", description: "Develop WordPress websites and plugins for hosting clients. Work with themes, custom plugins, and WooCommerce. Stable career in web development with large market demand." },
  { id: 60, title: "AR/VR Developer Intern", company: "Meta (Facebook)", location: "Hyderabad", mode: "Hybrid", experience: "Fresher", skills: ["Unity", "C#", "AR/VR", "3D Graphics"], source: "LinkedIn", postedDaysAgo: 1, salaryRange: "₹40k–₹60k/month Internship", applyUrl: "https://meta.com/careers/arvr", description: "Build augmented and virtual reality experiences for Meta's platforms. Work with Unity, Oculus SDK, and 3D graphics. Cutting-edge technology with global impact and premium compensation." }
];
